### ISSUE TITLE
Stuff TODO before hack can be merged back into develop

### ISSUE THREAD

**Issue by PoroCYon** [TerrariaPrismTeam/Prism#25]
* [x] #24 
* [x] Make Prism use a separate `input profiles.json` file, instead of vanilla's
* [x] [A few hooks in Main](https://github.com/TerrariaPrismTeam/Prism/blob/hack/Prism.Injector/Patcher/MainPatcher.cs#L725)
* [x] `./find-todos.sh`
  * [x] Proper WAV reading
  * [x] Complete Projectile AIStyles
  * [x] Complete NPC AIStyles
* ~~[ ] Reenable certain hooks~~ They haven't been enabled for quite a while.
  * ~~[ ] `ItemBehaviour.CanUse`~~
  * ~~[ ] `ItemBehaviour.UseItem`~~
* [x] Replace as much `if (dict.ContainsKey(foo)) DoStuff(dict[foo]);` with `TryGetValue`
* ~~[ ] Make chest loading faster~~ Seems to be as fast as I can get it to be...
* [x] Make ammo types not suck
